### ISSUE TITLE
windows_x86_64/libtensorflowlite.so.if.lib

### ISSUE THREAD

**Issue by fengyanWang** [pntt3011/mediapipe_face_iris_cpp#1]
hello!The download link given is the result of compilation for X86_Linux. Could you provide the download for X86_WIN

**Comment by pntt3011** [comment]
I'm so sorry for my mistake! I've updated it with the prebuilt library for Window.
However, I only tested it on Window 64-bit. If you're going to run it on 32-bit version, could you tell me whether it works or not?

**Comment by fengyanWang** [comment]
> I'm so sorry for my mistake! I've updated it with the prebuilt library for Window.
> However, I only tested it on Window 64-bit. If you're going to run it on 32-bit version, could you tell me whether it works or not?

**Comment by fengyanWang** [comment]
Hello, thank you very much for your reply! After replacing the lib file you provided, the system displays the following error：
![2021-08-23_143907](https://user-images.githubusercontent.com/36984088/130401967-9accd80d-64e4-4fca-b4d0-9f5aae654ba4.jpg)

**Comment by pntt3011** [comment]
I've checked about it. It seems that the prebuilt OPENCV libs do not contain the x86 version. You can try install it using cmake: https://docs.opencv.org/master/d3/d52/tutorial_windows_install.html

**Comment by pntt3011** [comment]
I will take note about it in the README file.

**Comment by fengyanWang** [comment]
> I will take note about it in the README file.

Ok, thank you very much
