### ISSUE TITLE
How did you manage to get the models as tflite?

### ISSUE THREAD

**Issue by hot-cat** [pntt3011/mediapipe_face_iris_cpp#23]
I wonder how you transformed the mediapipe models to tflite ones.

**Comment by pntt3011** [comment]
Hi @hot-cat, the tflite models had been public on their official repository. They just removed them a few months ago. You can find their links in this [issue](https://github.com/pntt3011/mediapipe_face_iris_cpp/issues/15).

**Comment by hot-cat** [comment]
Thanks a lot!!
