### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joelpaulkoch** [pntt3011/mediapipe_face_iris_cpp#4]
Hi, good job, thank you for that.
If you want to allow others to use it, you should consider adding a license to it.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Otherwise it won't be possible because of copyright laws.

**Comment by pntt3011** [comment]
Thank you for letting me know. 
I just created this repo for my hobby at first so I haven't thought about it.
