### ISSUE TITLE
tensorflow 2.4.4 and bazel build //tensorflow:libtensorflow_cc.so in MacOs 12.1

### ISSUE THREAD

**Issue by chfeizy** [pntt3011/mediapipe_face_iris_cpp#5]
bug ld: warning: dylib (/private/var/tmp/_bazel_also/c6fd75dad1daa641f8f9e0b5d840292d/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/libtensorflow_cc.so) was built for newer macOS version (12.1) than being linked (12.0)
ld: warning: dylib (/private/var/tmp/_bazel_also/c6fd75dad1daa641f8f9e0b5d840292d/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/libtensorflow_framework.2.dylib) was built for newer macOS version (12.1) than being linked (12.0)
Undefined symbols for architecture x86_64:

**Comment by pntt3011** [comment]
I'm sorry that I can't help you with your problem. I don't have any laptop that uses MacOS.
You can refer this repo: https://github.com/milinddeore/mediapipe-face-detector-cpp or ask the author if he can send you his prebuilt library (I don't know if it works like in windows).

**Comment by chfeizy** [comment]
use this 
bazel build -c opt //tensorflow/lite:libtensorflowlite.dylib
is success
